# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0','10.0', '11.0', '12.0', '13.0'

target 'CustomLoginDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomLoginDemo

	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'	
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'

end
